-- AlterTable
ALTER TABLE `km1` ADD COLUMN `ttd__ptj` INTEGER NULL,
    ADD COLUMN `ttd_katim` INTEGER NULL,
    ADD COLUMN `ttd_ppj` INTEGER NULL;

-- AlterTable
ALTER TABLE `km2` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `ttd_kasubag_umum` INTEGER NULL,
    ADD COLUMN `ttd_ppj` INTEGER NULL,
    ADD COLUMN `ttd_sekretaris` INTEGER NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `km3` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `ttd_katim` INTEGER NULL,
    ADD COLUMN `ttd_pt` INTEGER NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE `KM1` ADD CONSTRAINT `KM1_ttd_katim_fkey` FOREIGN KEY (`ttd_katim`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KM1` ADD CONSTRAINT `KM1_ttd_ppj_fkey` FOREIGN KEY (`ttd_ppj`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KM1` ADD CONSTRAINT `KM1_ttd__ptj_fkey` FOREIGN KEY (`ttd__ptj`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KM2` ADD CONSTRAINT `KM2_ttd_kasubag_umum_fkey` FOREIGN KEY (`ttd_kasubag_umum`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KM2` ADD CONSTRAINT `KM2_ttd_ppj_fkey` FOREIGN KEY (`ttd_ppj`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KM2` ADD CONSTRAINT `KM2_ttd_sekretaris_fkey` FOREIGN KEY (`ttd_sekretaris`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KM3` ADD CONSTRAINT `KM3_ttd_katim_fkey` FOREIGN KEY (`ttd_katim`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KM3` ADD CONSTRAINT `KM3_ttd_pt_fkey` FOREIGN KEY (`ttd_pt`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
